# Generated by Django 5.1.6 on 2025-02-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_rôle_usercustomer_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustomer',
            old_name='role',
            new_name='rôle',
        ),
    ]
